#ifndef QFILESYSTEMMODEL_GLOBAL_H
#define QFILESYSTEMMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QFILESYSTEMMODEL_LIBRARY)
#  define QFILESYSTEMMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QFILESYSTEMMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QFILESYSTEMMODEL_GLOBAL_H
